#!/bin/bash
# Author: Daniel Anderson
# Date: 6/17/2020
# Description: This script will run basic admin commands
# Date Modified: 06/17/2020

echo
echo This script will run basic administrative commands
echo
top | head -10
echo
df -h
echo
uptime
echo
iostat
echo
echo End of script